### ISSUE TITLE
In file: dynatrace-api/ExcelExport/dt-excel.py, column_cells[0].column should be column_cells[0].column_letter

### ISSUE THREAD

**Issue by sercero** [Dynatrace/dynatrace-api#15]
In line 108 of file dynatrace-api/ExcelExport/dt-excel.py,  column_cells[0].column returns a column number but ws.column_dimensions[] should be indexed with a string.

# python dt-excel.py
Status: 200
Status: 200
Traceback (most recent call last):
  File "dt-excel.py", line 108, in <module>
    ws.column_dimensions[column_cells[0].column].width = length+1
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/openpyxl/utils/bound_dictionary.py", line 26, in _getitem_
    setattr(value, self.reference, key)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/openpyxl/descriptors/base.py", line 44, in _set_
    raise TypeError('expected ' + str(self.expected_type))
TypeError: expected <type 'basestring'>

# python -V
Python 2.7.13

**Comment by myieye** [comment]
Closed due to inactivity
